{% set PKG_NAME = 'dropbot' %}
{% set PLATFORMIO_ENVS = 'teensy31'.split(' ') %}
{% set LIB_NAME = 'Dropbot' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}

{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  noarch: python
  entry_points:
    # .. versionadded:: 1.28
    - dropbot-self-test = dropbot.bin.self_test:main
    # .. versionadded:: 1.29
    - dropbot-upload = dropbot.bin.upload:upload
  script:
    # Generate Arduino code
    - python -m paver generate_all_code
    # Copy Arduino library to Conda include directory
    - python -c
        "import os.path; import os; import shutil; import platformio_helpers as pioh;
        lib_src_dir = os.path.join(os.environ['SRC_DIR'], 'lib',
                                   '{{ LIB_NAME }}');
        install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
        shutil.copytree(lib_src_dir, install_dir);
        "
    # Build firmware
    - python -m paver build_firmware
    # Copy compiled firmware to Conda bin directory
    - python -c
        "import os.path; import os; import shutil; import platformio_helpers as pioh;
        SRC_DIR = os.environ['SRC_DIR'];
        SRC_DIR = os.environ['SRC_DIR'];
        PIO_BIN_DIR = pioh.conda_bin_path().joinpath('{{ PKG_NAME }}');
        created = (None if os.path.isdir(PIO_BIN_DIR)
                   else os.makedirs(PIO_BIN_DIR));
        shutil.copy2(os.path.join(SRC_DIR, 'platformio.ini'),
                     os.path.join(PIO_BIN_DIR, 'platformio.ini'));
        {% for pio_platform in PLATFORMIO_ENVS -%}
        HEX_DIR = os.path.join(PIO_BIN_DIR, '{{ pio_platform }}');
        os.makedirs(HEX_DIR);
        shutil.copy2(os.path.join(SRC_DIR, '.pioenvs', '{{ pio_platform }}',
                                  'firmware.hex'),
                      os.path.join(PIO_BIN_DIR, '{{ pio_platform }}',
                                   'firmware.hex'));
        {%- endfor %}
        "
    # Generate `setup.py` from `pavement.py` definition.
    - python -m paver generate_setup
    # Install source directory as Python package.
    - python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - arduino-linked-list >=1.2.3
    - arduino-fast-digital
    - arduino-slow-soft-wire
    - arduino-slow-soft-i2c-master
    # ..versionadded:: 1.31
    # ..versionchanged:: 1.40
    # ..versionchanged:: 1.40.3
    # ..versionchanged:: 1.41
    - base-node-rpc >=0.46.2
    - future
    - json-tricks
    #: .. versionadded:: 1.47
    - logging-helpers
    #: .. versionadded:: 1.47
    - matplotlib
    - nanopb-helpers >=0.11.1
    - path_helpers
    - paver
    - pandoc
    - pip
    - platformio
    - platformio-framework-arduinoteensy >=1.136.0
    #: ..versionchanged:: 0.48
    - platformio-helpers >=0.10
    - platformio-platform-teensy >=2.0.0
    - platformio-tool-scons
    - platformio-tool-teensy >=1.21.0
    - platformio-toolchain-gccarmnoneeabi >=1.50401.0
    # .. versionchanged:: 1.37.2
    - protobuf >=3.5
    - pytables
    - python
    # ..versionchanged:: 1.33
    - serial-device >=0.9
    # ..versionchanged:: 1.37.3
    - teensy-minimal-rpc >=0.6.1

# .. versionadded:: 1.48
#     Split into `noarch` C++ header package and platform-specific Python
#     package.
outputs:
  - name: {{ PKG_NAME }}-dev
    noarch: generic
    files:
      - share
    requirements:
      run:
        - arduino-linked-list >=1.2.3
        - arduino-fast-digital
        - arduino-slow-soft-wire >=1.0.1
        - base-node-dev >=0.13.1
        - base-node-rpc-dev >=0.46.2
        - platformio-tool-scons
        - platformio-tool-teensy >=1.21.0
        - teensy-minimal-rpc-dev >=0.8.1
  - name: {{ PKG_NAME }}
    noarch: python
    files:
      - Lib/site-packages/{{ MODULE_NAME }}
    requirements:
      run:
        - {{ pin_subpackage(PKG_NAME + '-dev', max_pin='x.x') }}
        - base-node >=0.13.1
        - conda-helpers >=0.20
        - json-tricks
        #: .. versionadded:: 1.47
        - logging-helpers
        #: .. versionadded:: 1.47
        - matplotlib
        - nanopb-helpers >=0.11.1
        - pandoc
        - path_helpers
          #: ..versionchanged:: 0.48
        - platformio-helpers >=0.10
        # .. versionchanged:: 1.37.2
        - protobuf >=3.5
        - pytables
        - python
        # ..versionchanged:: 1.33
        - serial-device >=0.9
        # ..versionchanged:: 1.37.3
        - teensy-minimal-rpc >=0.8.2
    test:
      imports:
        # .. versionchanged:: 1.37.2
        - dropbot
        - dropbot._version
        - dropbot.bin
        - dropbot.config
        - dropbot.hardware_test
        - dropbot.metadata
        - dropbot.proxy
        - dropbot.state
      commands:
        - python -c
            "import sys; import os.path; import os; import shutil; import platformio_helpers as pioh;
            PIO_BIN_DIR = pioh.conda_bin_path().joinpath('{{ PKG_NAME }}');
            {% for pio_platform in PLATFORMIO_ENVS -%}
            HEX_DIR = os.path.join(PIO_BIN_DIR, '{{ pio_platform }}');
            HEX_PATH = os.path.join(HEX_DIR, 'firmware.hex');
            sys.exit(-1) if not os.path.isfile(HEX_PATH) else 0;
            {%- endfor %}
            "


about:
  home: https://gitlab.com/sci-bots/dropbot.py
  license: MIT
