# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dropbot-dx
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.0
{% endif %}

requirements:
  build:
    - teensy-minimal-rpc >=0.3.0
    - future
    - paver
    - pip
    - platformio
    - python 2.7*

  run:
    - teensy-minimal-rpc >=0.3.0
    - python 2.7*

about:
  home: https://github.com/wheeler-microfluidics/dropbot-dx
  license: MIT
