{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dropbot
  version: {{ GIT_VERSION }}

build:
  entry_points:
    # .. versionadded:: 1.28
    - dropbot-self-test = dropbot.bin.self_test:main
    # .. versionadded:: 1.29
    - dropbot-upload = dropbot.bin.upload:upload

requirements:
  build:
    - arduino-linked-list >=1.2.3
    - arduino-fast-digital
    - arduino-slow-soft-wire
    # ..versionadded:: 1.31
    # ..versionchanged:: 1.40
    # ..versionchanged:: 1.40.3
    # ..versionchanged:: 1.41
    - base-node-rpc >=0.41.1
    - future
    - json-tricks
    - nanopb-helpers >=0.6
    - paver
    - pandoc
    - pip
    - platformio-framework-arduinoteensy >=1.136.0
    - platformio-helpers >=0.3
    - platformio-platform-teensy >=2.0.0
    - platformio-tool-scons
    - platformio-tool-teensy >=1.21.0
    - platformio-toolchain-gccarmnoneeabi
    # .. versionchanged:: 1.37.2
    - protobuf >=3.5
    - pytables
    - python 2.7*
    # ..versionchanged:: 1.33
    - serial-device >=0.9
    # ..versionchanged:: 1.37.3
    - teensy-minimal-rpc >=0.6.1

  run:
    - arduino-linked-list >=1.2.3
    - arduino-fast-digital
    - arduino-slow-soft-wire
    - base-node
    # ..versionadded:: 1.31
    # ..versionchanged:: 1.37
    # ..versionchanged:: 1.40
    # ..versionchanged:: 1.40.2
    # ..versionchanged:: 1.40.3
    # ..versionchanged:: 1.41
    - base-node-rpc >=0.41.1
    - json-tricks
    - nanopb-helpers >=0.6
    - pandoc
    - platformio-helpers >=0.3
    - platformio-tool-scons
    - platformio-tool-teensy >=1.21.0
    # .. versionchanged:: 1.37.2
    - protobuf >=3.5
    - pytables
    - python 2.7*
    # ..versionchanged:: 1.33
    - serial-device >=0.9
    # ..versionchanged:: 1.37.3
    - teensy-minimal-rpc >=0.6.1

test:
  imports:
    # .. versionchanged:: 1.37.2
    - dropbot
    - dropbot._version
    - dropbot.bin
    - dropbot.config
    - dropbot.hardware_test
    - dropbot.metadata
    - dropbot.proxy
    - dropbot.state

about:
  home: https://gitlab.com/sci-bots/dropbot.py
  license: MIT
